// 系统设置-材料类设置 分类图标组件
// 从 page.tsx 渐进拆出的材料分类图标映射与展示组件。

"use client";

import {
  AirVent,
  AlignVerticalSpaceAround,
  Antenna,
  Archive,
  Armchair,
  Bath,
  BadgeCheck,
  BetweenHorizontalStart,
  Blinds,
  Blocks,
  BoxSelect,
  BrickWall,
  Brush,
  Cable,
  CircleEllipsis,
  CircleGauge,
  CircleDot,
  CloudRain,
  Cog,
  Columns3,
  ClipboardCheck,
  ClipboardList,
  Construction,
  Container,
  CookingPot,
  CornerDownRight,
  CornerUpRight,
  DoorClosed,
  DoorOpen,
  Droplets,
  Drill,
  Fence,
  Flower2,
  Frame,
  GalleryVertical,
  Gem,
  Grid2X2,
  Grid3X3,
  Hammer,
  HandPlatter,
  HardHat,
  Home,
  House,
  HousePlug,
  Image,
  KeyRound,
  LampCeiling,
  LampFloor,
  Landmark,
  Layers,
  Layers2,
  Layers3,
  LayoutGrid,
  Package,
  PackageOpen,
  PaintBucket,
  Paintbrush,
  Paintbrush2,
  PaintbrushVertical,
  PaintRoller,
  Palette,
  PanelLeft,
  PanelTop,
  PanelTopClose,
  Pipette,
  Plug,
  PlugZap,
  Router,
  ScanLine,
  Shield,
  ShowerHead,
  Shapes,
  Sofa,
  Sparkles,
  Spline,
  SquareStack,
  TableProperties,
  ToyBrick,
  Trees,
  Truck,
  Umbrella,
  UtilityPole,
  Wallpaper,
  WashingMachine,
  Waves,
  Wrench,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Category } from "./category-editor-dialog";

const materialCategoryIconMeta = {
  hydro: { className: "material-category-icon-hydro", label: "水电材料", icon: Droplets },
  masonry: { className: "material-category-icon-masonry", label: "泥瓦材料", icon: BrickWall },
  carpentry: { className: "material-category-icon-carpentry", label: "木作板材", icon: Layers },
  coating: { className: "material-category-icon-coating", label: "油漆涂料", icon: PaintBucket },
  tileStone: { className: "material-category-icon-tile-stone", label: "瓷砖石材", icon: Gem },
  floorDoor: { className: "material-category-icon-floor-door", label: "地板木门", icon: House },
  bathroom: { className: "material-category-icon-bathroom", label: "卫浴洁具", icon: Bath },
  electricHardware: { className: "material-category-icon-electric-hardware", label: "电器五金", icon: Plug },
  customCabinet: { className: "material-category-icon-custom-cabinet", label: "定制柜类", icon: Blocks },
  softDecor: { className: "material-category-icon-soft-decor", label: "软装配饰", icon: Sofa },
  generalOther: { className: "material-category-icon-general-other", label: "综合其他", icon: Archive },
  strongCable: { className: "material-category-icon-strong-cable", label: "强电线缆", icon: Cable },
  weakCable: { className: "material-category-icon-weak-cable", label: "弱电线缆", icon: Antenna },
  powerDevice: { className: "material-category-icon-power-device", label: "强电设备", icon: PlugZap },
  weakBox: { className: "material-category-icon-weak-box", label: "弱电箱体", icon: Router },
  breaker: { className: "material-category-icon-breaker", label: "电气保护器件", icon: BadgeCheck },
  conduitBox: { className: "material-category-icon-conduit-box", label: "线管线盒", icon: UtilityPole },
  waterPipe: { className: "material-category-icon-water-pipe", label: "给水管件", icon: Waves },
  drainPipe: { className: "material-category-icon-drain-pipe", label: "排水管件", icon: CloudRain },
  toolConsumable: { className: "material-category-icon-tool-consumable", label: "工具耗材", icon: Drill },
  mortar: { className: "material-category-icon-mortar", label: "水泥砂浆", icon: Package },
  brick: { className: "material-category-icon-brick", label: "砖砌材料", icon: ToyBrick },
  tileAdhesive: { className: "material-category-icon-tile-adhesive", label: "瓷砖胶背胶", icon: Grid2X2 },
  grout: { className: "material-category-icon-grout", label: "填缝美缝", icon: Paintbrush },
  leveling: { className: "material-category-icon-leveling", label: "找平材料", icon: AlignVerticalSpaceAround },
  waterproof: { className: "material-category-icon-waterproof", label: "防水材料", icon: Umbrella },
  floorDrain: { className: "material-category-icon-floor-drain", label: "地漏辅件", icon: CircleGauge },
  ecoBoard: { className: "material-category-icon-eco-board", label: "生态板免漆板", icon: PanelTop },
  plywood: { className: "material-category-icon-plywood", label: "多层板", icon: Layers3 },
  gypsumBoard: { className: "material-category-icon-gypsum-board", label: "石膏板", icon: PanelTopClose },
  keel: { className: "material-category-icon-keel", label: "轻钢龙骨", icon: Fence },
  woodLine: { className: "material-category-icon-wood-line", label: "木方木线", icon: Spline },
  glue: { className: "material-category-icon-glue", label: "木作胶粘剂", icon: Pipette },
  trim: { className: "material-category-icon-trim", label: "收口辅料", icon: CornerDownRight },
  putty: { className: "material-category-icon-putty", label: "腻子粉", icon: PackageOpen },
  latexPaint: { className: "material-category-icon-latex-paint", label: "乳胶漆", icon: PaintRoller },
  primerPaint: { className: "material-category-icon-primer-paint", label: "底漆面漆", icon: PaintbrushVertical },
  artPaint: { className: "material-category-icon-art-paint", label: "艺术漆", icon: Palette },
  woodPaint: { className: "material-category-icon-wood-paint", label: "木器漆", icon: Brush },
  wallPrimer: { className: "material-category-icon-wall-primer", label: "墙固界面剂", icon: Shield },
  paintTool: { className: "material-category-icon-paint-tool", label: "油漆辅料", icon: Paintbrush2 },
  wallTile: { className: "material-category-icon-wall-tile", label: "墙砖", icon: Grid3X3 },
  floorTile: { className: "material-category-icon-floor-tile", label: "地砖", icon: LayoutGrid },
  slab: { className: "material-category-icon-slab", label: "岩板大板", icon: SquareStack },
  thresholdStone: { className: "material-category-icon-threshold-stone", label: "过门石窗台石", icon: Landmark },
  skirting: { className: "material-category-icon-skirting", label: "踢脚线", icon: ScanLine },
  stoneAccessory: { className: "material-category-icon-stone-accessory", label: "石材辅料", icon: Shapes },
  cornerTrim: { className: "material-category-icon-corner-trim", label: "阳角线收边条", icon: CornerUpRight },
  laminateFloor: { className: "material-category-icon-laminate-floor", label: "强化地板", icon: LayoutGrid },
  engineeredFloor: { className: "material-category-icon-engineered-floor", label: "实木复合地板", icon: Layers2 },
  solidFloor: { className: "material-category-icon-solid-floor", label: "实木地板", icon: Trees },
  indoorDoor: { className: "material-category-icon-indoor-door", label: "室内门", icon: DoorOpen },
  doorFrame: { className: "material-category-icon-door-frame", label: "门套窗套", icon: PanelLeft },
  doorHardware: { className: "material-category-icon-door-hardware", label: "门锁合页", icon: KeyRound },
  floorTrim: { className: "material-category-icon-floor-trim", label: "踢脚线压条", icon: BetweenHorizontalStart },
  toilet: { className: "material-category-icon-toilet", label: "马桶", icon: CircleDot },
  vanity: { className: "material-category-icon-vanity", label: "浴室柜", icon: TableProperties },
  showerFaucet: { className: "material-category-icon-shower-faucet", label: "花洒龙头", icon: ShowerHead },
  basinSink: { className: "material-category-icon-basin-sink", label: "台盆水槽", icon: Droplets },
  showerRoom: { className: "material-category-icon-shower-room", label: "淋浴房隔断", icon: GalleryVertical },
  bathroomHardware: { className: "material-category-icon-bathroom-hardware", label: "五金挂件", icon: HandPlatter },
  bathroomAccessory: { className: "material-category-icon-bathroom-accessory", label: "卫浴配件", icon: BoxSelect },
  switchSocket: { className: "material-category-icon-switch-socket", label: "开关插座", icon: HousePlug },
  lighting: { className: "material-category-icon-lighting", label: "照明灯具", icon: LampCeiling },
  kitchenBathAppliance: { className: "material-category-icon-kitchen-bath-appliance", label: "厨卫电器", icon: CookingPot },
  hvac: { className: "material-category-icon-hvac", label: "中央空调新风", icon: AirVent },
  smartHome: { className: "material-category-icon-smart-home", label: "智能家居", icon: Home },
  baseHardware: { className: "material-category-icon-base-hardware", label: "基础五金", icon: Hammer },
  installAccessory: { className: "material-category-icon-install-accessory", label: "安装辅件", icon: Wrench },
  kitchenCabinet: { className: "material-category-icon-kitchen-cabinet", label: "橱柜", icon: Container },
  wardrobe: { className: "material-category-icon-wardrobe", label: "衣柜", icon: Columns3 },
  entryCabinet: { className: "material-category-icon-entry-cabinet", label: "玄关柜", icon: DoorClosed },
  balconyCabinet: { className: "material-category-icon-balcony-cabinet", label: "阳台柜", icon: Flower2 },
  bathroomCabinet: { className: "material-category-icon-bathroom-cabinet", label: "浴室柜", icon: BoxSelect },
  cabinetDoor: { className: "material-category-icon-cabinet-door", label: "柜门板材", icon: Frame },
  customHardware: { className: "material-category-icon-custom-hardware", label: "定制五金", icon: Cog },
  curtain: { className: "material-category-icon-curtain", label: "窗帘布艺", icon: Blinds },
  wallpaper: { className: "material-category-icon-wallpaper", label: "墙纸墙布", icon: Wallpaper },
  furniture: { className: "material-category-icon-furniture", label: "家具", icon: Armchair },
  softLight: { className: "material-category-icon-soft-light", label: "灯饰软装", icon: LampFloor },
  decorArt: { className: "material-category-icon-decor-art", label: "装饰画摆件", icon: Image },
  homeDecor: { className: "material-category-icon-home-decor", label: "家居饰品", icon: Sparkles },
  softInstall: { className: "material-category-icon-soft-install", label: "软装安装辅料", icon: Drill },
  protection: { className: "material-category-icon-protection", label: "成品保护", icon: ClipboardCheck },
  temporaryFacility: { className: "material-category-icon-temporary-facility", label: "临时设施", icon: Construction },
  moving: { className: "material-category-icon-moving", label: "搬运上楼", icon: Truck },
  cleaning: { className: "material-category-icon-cleaning", label: "清洁保洁", icon: WashingMachine },
  consumable: { className: "material-category-icon-consumable", label: "施工耗材", icon: ClipboardList },
  safety: { className: "material-category-icon-safety", label: "安全文明", icon: HardHat },
  miscellaneous: { className: "material-category-icon-miscellaneous", label: "其他杂项", icon: CircleEllipsis },
  tile: { className: "material-category-icon-tile", label: "瓷砖/砖材", icon: Grid2X2 },
  wood: { className: "material-category-icon-wood", label: "木材/木作", icon: Trees },
  pipe: { className: "material-category-icon-pipe", label: "水管/管材", icon: Waves },
  wire: { className: "material-category-icon-wire", label: "电线/电料", icon: Cable },
  light: { className: "material-category-icon-light", label: "灯具照明", icon: LampCeiling },
  hardware: { className: "material-category-icon-hardware", label: "五金配件", icon: Hammer },
  paint: { className: "material-category-icon-paint", label: "油漆涂料", icon: PaintBucket },
  sanitary: { className: "material-category-icon-sanitary", label: "卫浴洁具", icon: ShowerHead },
  stone: { className: "material-category-icon-stone", label: "石材", icon: Gem },
  board: { className: "material-category-icon-board", label: "板材", icon: PanelTop },
  cement: { className: "material-category-icon-cement", label: "水泥砂浆", icon: Package },
  door: { className: "material-category-icon-door", label: "门窗", icon: DoorOpen },
  cabinet: { className: "material-category-icon-cabinet", label: "橱柜定制", icon: Blocks },
  floor: { className: "material-category-icon-floor", label: "地板地面", icon: LayoutGrid },
  glass: { className: "material-category-icon-glass", label: "玻璃镜面", icon: PanelLeft },
  fabric: { className: "material-category-icon-fabric", label: "软装布艺", icon: Blinds },
  general: { className: "material-category-icon-general", label: "材料分类", icon: Archive },
} satisfies Record<string, { className: string; label: string; icon: LucideIcon }>;

export type MaterialCategoryIconKind = keyof typeof materialCategoryIconMeta;

const materialCategoryExactIconMap: Record<string, MaterialCategoryIconKind> = {
  水电材料: "hydro",
  强电线缆: "strongCable",
  弱电线缆: "weakCable",
  强电设备: "powerDevice",
  弱电箱体: "weakBox",
  电气保护器件: "breaker",
  线管线盒: "conduitBox",
  给水管件: "waterPipe",
  排水管件: "drainPipe",
  水电工具耗材: "toolConsumable",
  泥瓦材料: "masonry",
  水泥砂浆: "mortar",
  砖砌材料: "brick",
  瓷砖胶背胶: "tileAdhesive",
  填缝美缝: "grout",
  找平材料: "leveling",
  防水材料: "waterproof",
  地漏辅件: "floorDrain",
  木作板材: "carpentry",
  生态板免漆板: "ecoBoard",
  多层板: "plywood",
  石膏板: "gypsumBoard",
  轻钢龙骨: "keel",
  木方木线: "woodLine",
  木作胶粘剂: "glue",
  收口辅料: "trim",
  油漆涂料: "coating",
  腻子粉: "putty",
  乳胶漆: "latexPaint",
  底漆面漆: "primerPaint",
  艺术漆: "artPaint",
  木器漆: "woodPaint",
  墙固界面剂: "wallPrimer",
  油漆辅料: "paintTool",
  瓷砖石材: "tileStone",
  墙砖: "wallTile",
  地砖: "floorTile",
  岩板大板: "slab",
  过门石窗台石: "thresholdStone",
  踢脚线: "skirting",
  石材辅料: "stoneAccessory",
  阳角线收边条: "cornerTrim",
  地板木门: "floorDoor",
  强化地板: "laminateFloor",
  实木复合地板: "engineeredFloor",
  实木地板: "solidFloor",
  室内门: "indoorDoor",
  门套窗套: "doorFrame",
  门锁合页: "doorHardware",
  踢脚线压条: "floorTrim",
  卫浴洁具: "bathroom",
  马桶: "toilet",
  浴室柜: "vanity",
  花洒龙头: "showerFaucet",
  台盆水槽: "basinSink",
  淋浴房隔断: "showerRoom",
  五金挂件: "bathroomHardware",
  卫浴配件: "bathroomAccessory",
  电器五金: "electricHardware",
  开关插座: "switchSocket",
  照明灯具: "lighting",
  厨卫电器: "kitchenBathAppliance",
  中央空调新风: "hvac",
  智能家居: "smartHome",
  基础五金: "baseHardware",
  安装辅件: "installAccessory",
  定制柜类: "customCabinet",
  橱柜: "kitchenCabinet",
  衣柜: "wardrobe",
  玄关柜: "entryCabinet",
  阳台柜: "balconyCabinet",
  柜门板材: "cabinetDoor",
  定制五金: "customHardware",
  软装配饰: "softDecor",
  窗帘布艺: "curtain",
  墙纸墙布: "wallpaper",
  家具: "furniture",
  灯饰软装: "softLight",
  装饰画摆件: "decorArt",
  家居饰品: "homeDecor",
  软装安装辅料: "softInstall",
  综合其他: "generalOther",
  成品保护: "protection",
  临时设施: "temporaryFacility",
  搬运上楼: "moving",
  清洁保洁: "cleaning",
  施工耗材: "consumable",
  安全文明: "safety",
  其他杂项: "miscellaneous",
};

export function getMaterialCategoryIconKind(category: Category): MaterialCategoryIconKind {
  const name = `${category.name || ""}`.trim();
  const parentName = `${category.parent_name || ""}`.trim();
  if (name === "浴室柜" && /定制|柜类/.test(parentName)) return "bathroomCabinet";

  const exactKind = materialCategoryExactIconMap[name];
  if (exactKind) return exactKind;

  const text = `${category.name || ""} ${parentName}`.toLowerCase();
  if (/墙砖|地砖|瓷|砖|马赛克/.test(text)) return "tile";
  if (/实木|木材|木方|木线|木制|木饰/.test(text)) return "wood";
  if (/排水|给水|水管|管材|ppr|pvc|阀|地漏/.test(text)) return "pipe";
  if (/弱电|强电|电线|电缆|开关|插座|配电|线管/.test(text)) return "wire";
  if (/灯|照明|筒灯|射灯|灯带|吸顶/.test(text)) return "light";
  if (/五金|螺丝|合页|铰链|拉手|滑轨|锁|龙骨|挂件/.test(text)) return "hardware";
  if (/漆|涂料|乳胶|腻子|防水|胶|美缝/.test(text)) return "paint";
  if (/卫浴|洁具|马桶|花洒|浴室|浴柜|台盆|龙头/.test(text)) return "sanitary";
  if (/石|岩板|大理石|花岗岩|人造石/.test(text)) return "stone";
  if (/板|石膏板|欧松板|多层板|密度板|生态板/.test(text)) return "board";
  if (/水泥|砂|沙|浆|黄沙|河沙|红砖|砌块/.test(text)) return "cement";
  if (/门|窗|窗帘盒|门套|窗套/.test(text)) return "door";
  if (/柜|橱|衣柜|定制|台面/.test(text)) return "cabinet";
  if (/地板|木地板|踢脚|地面/.test(text)) return "floor";
  if (/玻璃|镜|淋浴房/.test(text)) return "glass";
  if (/软装|窗帘|布艺|墙布|墙纸/.test(text)) return "fabric";
  return "general";
}

export function MaterialCategoryIcon({ category, compact = false }: { category: Category; compact?: boolean }) {
  const kind = getMaterialCategoryIconKind(category);
  const meta = materialCategoryIconMeta[kind];
  const Icon = meta.icon;

  return (
    <span className={cn("material-category-icon-badge", compact && "material-category-icon-compact", meta.className)} title={meta.label} aria-label={meta.label}>
      <Icon aria-hidden="true" className="h-[17px] w-[17px]" strokeWidth={1.85} />
    </span>
  );
}

